# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20160320_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='time',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
